// BİLDİRİM SERVİSİ (G19 · Tur 27 · U-2, U-3, K-8, M-5, M-1, K-1, Ö-1, Ö-2, S-9). Kapı: scripts/gate-notify.mjs · kanarya: scripts/canary-notify.mts.
// TEK YÜZEY: bildirimi kuran tek yol `buildNotification`, gönderen tek yol `deliverNotification`. İkinci bir yol açan kod KIRMIZI (kapı).
// U-2 — KİLİT EKRANI: yük KAPALI ALAN LİSTESİDİR (`LOCK_SCREEN_FIELDS`). Tutar, bakiye, pozisyon büyüklüğü taşıyacak alan YOKTUR; bu metinde değil VERİ YAPISINDA zorlanır.
//   Görünen kısım yalnız `display` (başlık + kilit ekranı notu); `route` görünmez (yönlendirme). Üç cümle (`detail`) kilit ekranı yüküne HİÇ girmez: uygulama açılınca panelden okunur.
// U-2 — SÖZ: gecikmiş, tahmini, "muhtemelen" bildirim yok. Gönderim SENKRONDUR (durma yolunun içinde), kuyruk ve yeniden deneme YOKTUR. Gönderilemeyen bildirim "gönderildi" SAYILMAZ:
//   sonuç cümlesi (`Delivery.sentence`) durma olayının sebebine yazılır ⇒ olay ölçülebilir (K-8) ve ikinci bir satır açılmaz (A-9: durma başına Neon yazımı artmaz).
// U-2 — KAPATILAMAZ: İŞ SAHİBİ KARARIYLA GENİŞLEDİ (2026-09-12): "para güvenliğine dokunan kodlar muted_codes'a ALINAMAZ". Dört sınıf sicilden TÜRETİLDİ, sayılmadı: koruma bulunamadı
//   (`PROTECTION_FAILED` türü) · motor durdu ve stop tetiklendi (`STOPPED` türü; durdurma düğmesi `STOP_BUTTON` bu türdedir) · tavan doldu (`BUDGET_EXHAUSTED` türü) · anahtar geçersiz (`KEY_INVALID`).
//   `mutedCodes` bunları KAPSAMAZ ve kesen yer KODDUR (ayar satırına yazılsa bile yok sayılır). Varsayılan `NOTHING_MUTED` (kapalı-varsayılan).
// U-3 — metin sicilden gelir, koddan UYDURULMAZ: sicilde olup metni yazılmamış sebep sicilin kendi etiketini gösterir; sicilde HİÇ OLMAYAN kod için bildirim ÜRETİLMEZ.
// TAŞIYICI BİR ARAYÜZDÜR (`NotifyTransport`) ve BUGÜN YAPILANDIRILMAMIŞTIR — kapalı arızalanır: her gönderim başarısız döner, sonuç olaya yazılır, "gönderildi" ASLA sayılmaz.
//   ÖLÇÜLDÜ (Tur 28 madde 1, `vercel env ls` + `vercel env pull --environment=production`): üretimdeki 16 proje değişkeninin (37 ad) hiçbiri FCM/Firebase/push DEĞİL ⇒ taşıyıcı sözleşmesi YOK.
//   Olmayan bir sözleşmeye kod yazılmaz: GERÇEK KÖPRÜ İŞ SAHİBİ KARARIYLA BU TURA ALINMADI (2026-09-17) ve ortam adı UYDURULMADI. Bildirimin GİDECEĞİ ADRES (cihaz kaydı) bu turda yazıldı.
// TUR 28 (G20) — İKİ AYAR, İKİ YER: kapatma tercihi ve eleme penceresi `notify_settings` (Neon, `./settings.ts`); eleme penceresinin kendisi Upstash'te süreli anahtardır (`./dedup.ts`).
//   ELEME İŞ SAHİBİ KARARIDIR (2026-09-12): aynı sebep için 30 dakikada bir kez; farklı sebep etkilenmez; kapatılamaz kodlar muaftır (muafiyet de ayardır). SESSİZ SAAT YOKTUR (karar 3).
//   → TUR 29 (K1, 2026-09-17): tam muafiyet KALKTI — kapatılamaz sınıf kendi penceresiyle (2 dk) elenir, diğerleri 30 dk. İki sayı da ayardır (`notify_settings`).
import { STOP_REASONS, type RequestKind, type StopReasonCode } from "@/lib/events/stop-reasons";
import { upstashDedupStore, type DedupStore } from "./dedup";
import { human, loadNotifySettings, NOTIFY_STORE_BUDGET_MS, prismaNotifySettingsStore, type NotifySettingsStore } from "./settings";
import { readFirebaseEnv, type FirebaseEnv } from "@/lib/env";
import { prismaDeviceStore, type DeviceStore } from "./devices";
import { fcmTransport } from "./fcm";

export type Level = "INFO" | "WARN" | "ALARM";
/** Bir bildirimin metni (U-3): ne oldu · paraya etkisi ne · ne yapılacak. `title` kilit ekranına çıkar; `what`/`money`/`next` yalnız uygulama içindir. */
export type NotifyText = { level: Level; title: string; what: string; money: string; next: string };

/** SESSİZ SINIF (M-4): "pozisyon açılmadı" bir durma DEĞİL, geçerli bir çıktıdır ⇒ bildirim gerekmez. Her atlamayı bildiren servis U-2'nin sözünü tutamaz (kilit ekranı gürültüsü). */
export type SilentKind = "POSITION_SKIPPED";
/** Bildirim GEREKTİREN kodlar sicilden TÜRETİLİR (el listesi yok): sicile yeni bir sebep eklenince derleyici onun metnini ister. */
export type NotifiableCode = { [K in StopReasonCode]: (typeof STOP_REASONS)[K]["kind"] extends SilentKind ? never : K }[StopReasonCode];
export const ALL_CODES = Object.keys(STOP_REASONS) as StopReasonCode[];
export const NOTIFIABLE_CODES = ALL_CODES.filter((c) => STOP_REASONS[c].kind !== "POSITION_SKIPPED") as NotifiableCode[];
export const SILENT_CODES = ALL_CODES.filter((c) => STOP_REASONS[c].kind === "POSITION_SKIPPED");
/** İSTEK TÜRLERİNİN BİLDİRİM SINIFI (Tur 48, K-A `winvestor-kaldirac-istegi-ayrintilari` EK KARAR: bildirim HAYIR). Sahip isteği kendisi başlatır ve sonucu ekranda ANINDA görür; ikinci kanal
 *  17 Eyl bildirim elemesi kararının elemek istediği gürültüdür. Derleyiciye bağlı: yeni istek türü buraya sınıfı yazılmadan derlenmez. Bu türler durma sicilinde değildir ⇒ `buildNotification` onları tanımaz. */
export const REQUEST_KIND_NOTIFY = { LEVERAGE_REQUEST: "bildirimsiz", ENTRY_SWITCH_OPENED: "bildirimli" } as const satisfies Record<RequestKind, "bildirimsiz" | "bildirimli">;
/** TUR 65 (S64-1, K1 = [C], KARAR-DEFTERI 20 Eyl satır 81): istek türleri ekseni İKİ sınıf taşır. "bildirimli" istek türü durma sebebi DEĞİLDİR (motoru durdurmaz, durma kartına girmez)
 *  ama sahibine haber verilir: hassas eylemi başka biri yapmışsa sahip bunu ancak bildirimle öğrenir. Tur 48 emsali ("sahibin kendi başlattığı eylem bildirimsizdir") genel ve eskidir;
 *  20 Eyl kararı bu eylem için özel ve yenidir. Metni aşağıda, derleyiciye bağlı (bildirimli tür metinsiz derlenmez). Kapatılamaz sınıfa GİRMEZ: o sınıf durma sicilinin para güvenliği
 *  türlerinden TÜRETİLİR (`undismissable`), el listesi değildir. */
export type NotifiedRequestKind = { [K in RequestKind]: (typeof REQUEST_KIND_NOTIFY)[K] extends "bildirimli" ? K : never }[RequestKind];
export const isNotifiable = (code: string): code is NotifiableCode => (NOTIFIABLE_CODES as readonly string[]).includes(code);
/** PARA GÜVENLİĞİNE DOKUNAN TÜRLER (iş sahibi kararı 2026-09-12, U-2). Her biri sicilin KENDİ `kind` alanından gelir — el listesi değil: sicile bu türlerden yeni bir sebep eklenirse
 *  o da kendiliğinden kapatılamaz olur. "stop tetiklendi" ayrı bir tür değildir: durdurma düğmesi (`STOP_BUTTON`) sicilde `STOPPED` türündedir (ölçüldü, uydurulmadı). */
export const MONEY_SAFETY_KINDS = ["PROTECTION_FAILED", "STOPPED", "BUDGET_EXHAUSTED"] as const;
/** U-2 + iş sahibi kararı: para güvenliğine dokunan dört sınıf kapatılamaz. TÜRETİLDİ: koruma bulunamadı · motor durdu/stop tetiklendi · tavan doldu · anahtar geçersiz (`KEY_INVALID`). Sayılmadı. */
export const undismissable = (code: string): boolean => { const m = (STOP_REASONS as Record<string, { kind: string } | undefined>)[code]; return m !== undefined && ((MONEY_SAFETY_KINDS as readonly string[]).includes(m.kind) || code === "KEY_INVALID"); };
export const UNDISMISSABLE_CODES = NOTIFIABLE_CODES.filter((c) => undismissable(c));
/** Kapatma izni SORULUR, varsayılmaz. Tur 28: kapatma tercihinin SAKLANDIĞI yer iş sahibi kararıyla `notify_settings.muted_codes` (Neon) oldu; kapatılamaz kodları KAPSAMAZ (kesen yer burasıdır). */
export const canMute = (code: string): { allowed: false; rule: string; why: string } | { allowed: true } => undismissable(code)
  ? { allowed: false, rule: "U-2", why: "para güvenliğine dokunan bildirim kapatılamaz: koruma bulunamadı, motor durdu ya da stop tetiklendi, tavan doldu, anahtar geçersiz" } : { allowed: true };

/** SİCİLDEKİ SEBEBİN BİLDİRİM METNİ. Anahtarlar sicilden gelir (derleyici zorlar): yüzey sebep uyduramaz, yalnız sicildeki kodu insan cümlesine çevirir. Metinlerde rakam yoktur (U-2). */
export const NOTIFY_TEXT = {
  STOP_BUTTON: { level: "WARN", title: "Motoru sen durdurdun", what: "Durdurma düğmesi kullanıldı ve motor durdu.", money: "Yeni pozisyon açılmıyor ve komisyon harcanmıyor. Açık pozisyonlar ve borsadaki koruma emirleri olduğu gibi duruyor.", next: "Hazır olduğunda yeniden başlat; başlatma parolanı ve tek kullanımlık kodunu ister." },
  RESTART: { level: "INFO", title: "Motor yeniden başladı", what: "Motor yeniden başlatıldı ve çalışma izni yenilendi.", money: "Giriş yeniden açık: kurallar tuttuğunda pozisyon açılabilir ve komisyon harcanmaya başlar.", next: "Bir şey yapman gerekmiyor. Panelden ilk turun ne yaptığını görebilirsin." },
  HEALTH_PAUSED: { level: "WARN", title: "Sağlık kapısı kapandı: komisyon kârı yiyor", what: "Ödenen komisyonun brüt kâra oranı, pozisyon açarken kullanılan giriş ölçütünün altına düştü: strateji kendi kurduğu bahsi tutturamıyor.", money: "Strateji kendini duraklattı, yeni pozisyon açılmıyor. Çıkış ve borsadaki koruma emirleri sürüyor; açık pozisyonların yönetimi değişmedi.", next: "Oran eşiğin altına dönerse duraklama kendiliğinden kalkar. Paneldeki sağlık satırı oranı, eşiği ve kalan payı rakamla gösterir." },
  HEALTH_RECOVERED: { level: "INFO", title: "Sağlık kapısı yeniden açıldı", what: "Ödenen komisyonun brüt kâra oranı eşiğin altına döndü ve sağlık duraklaması kaldırıldı.", money: "Giriş yeniden açık: kurallar tuttuğunda yeni pozisyon açılır.", next: "Bir şey yapman gerekmiyor. Paneldeki sağlık satırı oranı rakamla gösterir." },
  HEALTH_UNKNOWN: { level: "ALARM", title: "Sağlık göstergesi ölçülemiyor", what: "Komisyon defteri ya da kapanan pozisyon kayıtları okunamadığı için ödenen komisyonun kâra oranı hesaplanamadı.", money: "Sağlıklı olduğu VARSAYILMADI: yeni pozisyon açılmıyor. Çıkış ve borsadaki koruma emirleri sürüyor.", next: "Kayıtlar okunduğunda hüküm yeniden verilir ve giriş kendiliğinden açılır." },
  PROTECTION_LOST: { level: "ALARM", title: "Koruma emri borsada bulunamadı", what: "Açık bir pozisyonun borsadaki zarar durdur emri bulunamadı: iptal edilmiş ya da düşmüş.", money: "Bu, paranın aşağı yönlü sigortasının kalkması demektir. Motor bu durumda pozisyonu derhal kapatır; kapatamazsa kendini durdurur ve seni bekler.", next: "Paneldeki pozisyon satırına bak: kapatıldıysa iş bitti, kapatılamadıysa pozisyonu borsadan elle kapat." },
  PROTECTION_FAILED: { level: "ALARM", title: "Koruma emri yerleşmedi, pozisyon kapatıldı", what: "Yeni açılan pozisyonun zarar durdur emri borsaya yerleştirilemedi; korumasız pozisyon tutulmadığı için pozisyon kapatıldı.", money: "Kapatma komisyonu ödendi ve pozisyon artık yok. Korumasız bekleme yapılmadı: kural gereği kapatmak, korumasız tutmaktan ucuzdur.", next: "Bir şey yapman gerekmiyor. Paneldeki pozisyon satırı kapanışı ve ödenen komisyonu rakamla gösterir." },
  PROTECTION_WINDOW_EXCEEDED: { level: "ALARM", title: "Koruma penceresi aşıldı, pozisyon kapatıldı", what: "Pozisyon açıldıktan sonra koruma emri için tanınan süre doldu; pozisyon o süre boyunca korumasız kaldığı için kapatıldı.", money: "Kapatma komisyonu ödendi ve pozisyon artık yok. Korumasız pozisyon tutulmadı.", next: "Bir şey yapman gerekmiyor. Paneldeki pozisyon satırı kapanışı ve ödenen komisyonu rakamla gösterir." },
  PROTECTION_UPDATE_FAILED: { level: "ALARM", title: "Koruma taşınamadı, pozisyon kapatıldı", what: "Fiyat yükseldiği için koruma emri yukarı taşınacaktı ya da çıkış emri gönderilecekti; yeni emir borsaya yerleşmedi.", money: "Pozisyon korumasız bırakılmadı: kapatıldı ve kapatma komisyonu ödendi.", next: "Bir şey yapman gerekmiyor. Paneldeki pozisyon satırı kapanışı ve ödenen komisyonu rakamla gösterir." },
  PROTECTION_UNVERIFIABLE: { level: "ALARM", title: "Koruma emri borsada doğrulanamadı", what: "Koruma emrinin borsada durup durmadığı sorulamadı; sorgu düştü.", money: "Emir doğrulanmadığı için korumasız sayıldı: motor durdu ve yeni pozisyon açmıyor. Emrin yerinde olduğu VARSAYILMADI.", next: "Borsa sorgusu döndüğünde durum yeniden ölçülür. Beklemek istemiyorsan koruma emrini borsanın kendi ekranından doğrula." },
  CLOSE_FAILED: { level: "ALARM", title: "Korumasız pozisyon kapatılamadı", what: "Koruması olmayan bir pozisyonun kapatılması gerekiyordu ve kapatma emri borsaya geçmedi.", money: "Pozisyon şu an borsada korumasız duruyor: aşağı yönlü sigortan yok. Motor kendini durdurdu ve yeni pozisyon açmıyor.", next: "Pozisyonu borsanın kendi ekranından elle kapat. Bu bildirim, elle müdahale gereken tek durumdur." },
  KEY_INVALID: { level: "ALARM", title: "Borsa anahtarı geçersiz", what: "Borsa, imzalı çağrıyı anahtarın geçersiz olduğu ya da yetkisinin düştüğü gerekçesiyle reddetti.", money: "Motor borsaya emir gönderemiyor: yeni pozisyon açılmaz ve çıkış emri de gönderilemez. Borsada duran koruma emirleri anahtara bağlı değildir, yerlerinde tetiklenirler.", next: "Borsanın ekranından anahtarın durumunu ve yetkilerini denetle; gerekirse yeni anahtar üret ve panelden tanıt." },
  KEY_EXPIRING: { level: "WARN", title: "Borsa anahtarı silinmeye yaklaşıyor", what: "Borsa, uzun süre emir göndermeyen anahtarları kendiliğinden siliyor; bu anahtar o sınıra yaklaştı.", money: "Şimdilik her şey çalışıyor. Anahtar silinirse motor emir gönderemez; borsada duran koruma emirleri yine yerinde kalır.", next: "Anahtar silinmeden önce panelden yeni bir anahtar tanıtman yeterli. Motorun bir emir göndermesi de sayacı sıfırlar." },
  REGION_BLOCKED: { level: "ALARM", title: "Borsa bu konumdan erişimi engelliyor", what: "Borsa, çağrının geldiği konumu kısıtlı bölge sayıp reddetti.", money: "Motor borsaya ulaşamıyor: yeni pozisyon açılmaz ve çıkış emri gönderilemez. Borsada duran koruma emirleri yerinde tetiklenir.", next: "Bu, kodun koştuğu bölgeyle ilgili bir ayardır ve yazılımın kendi başına düzeltebileceği bir şey değil; paneldeki sicil kaydını gördüğünü bize bildir." },
  IP_BANNED: { level: "ALARM", title: "Borsa erişimimizi geçici olarak kapattı", what: "Çok fazla çağrı yapıldığı için borsa adresimizi askıya aldı.", money: "Askı boyunca yeni pozisyon açılmaz ve çıkış emri gönderilemez. Borsada duran koruma emirleri askıdan etkilenmez, yerlerinde tetiklenir.", next: "Askı süresi dolunca erişim kendiliğinden döner. Paneldeki sicil kaydı askının ne zaman başladığını gösterir." },
  BUDGET_EXHAUSTED: { level: "INFO", title: "Borsaya çağrı bütçesi doldu", what: "Borsanın bir dakikada izin verdiği çağrı ağırlığı doldu ya da borsa bir süre beklememizi istedi.", money: "Bu bir arıza değil, borsanın kuralı. Bekleme boyunca yeni pozisyon açılmıyor; çıkış ve borsadaki koruma emirleri bu bütçeye hiç bakmaz.", next: "Bütçe kendiliğinden yenilenir ve motor kaldığı yerden sürer." },
  FEE_BUDGET_EXHAUSTED: { level: "INFO", title: "Dönemin komisyon bütçesi doldu", what: "Bu dönem ödenebilecek toplam komisyon için konan bütçe doldu.", money: "Yeni pozisyon açılmıyor; böylece komisyon erimesi duruyor. Çıkış ve borsadaki koruma emirleri bütçeye hiç bakmaz, çalışmaya devam eder.", next: "Bütçe bir sonraki dönemde yeniden ölçülen sermayeyle açılır. Paneldeki komisyon satırı ödenen tutarı rakamla gösterir." },
  FEE_RATE_UNAVAILABLE: { level: "WARN", title: "Komisyon oranı ölçülemedi", what: "Borsadan okunan komisyonun hangi kurla paraya çevrileceği ölçülemedi; kayıt çevrilmedi.", money: "Ödenen komisyon bilinmeden yeni pozisyon açılmıyor. Çıkış ve borsadaki koruma emirleri sürüyor.", next: "Kur okunduğunda kayıt tamamlanır ve giriş kendiliğinden açılır." },
  FEE_LEDGER_UNAVAILABLE: { level: "WARN", title: "Komisyon defteri okunamıyor", what: "Komisyon defteri ya da dönem sermayesi okunamadı; bütçenin ne kadarının harcandığı bilinmiyor.", money: "Bütçe bilinmeden yeni pozisyon açılmıyor. Çıkış ve borsadaki koruma emirleri sürüyor.", next: "Defter okunduğunda bütçe yeniden ölçülür ve giriş kendiliğinden açılır." },
  BRAIN_SPEND_CEILING: { level: "INFO", title: "Karar motorunun harcama tavanı doldu", what: "Karar motoru bu dönem için konan harcama tavanını ya da bugünkü çağrı tavanını doldurdu.", money: "Bu bir arıza değil, bilerek konmuş bir tavan: üstünde tek kuruş harcanmıyor. Yeni pozisyon açılmıyor; çıkış ve borsadaki koruma emirleri sürüyor.", next: "Tavan bir sonraki dönemde kendiliğinden sıfırlanır. Daha erken çalışmasını istiyorsan panelin ayar bölümünden daha ucuz bir model ya da daha seyrek bir sıklık seç." },
  BRAIN_SPEND_UNKNOWN: { level: "WARN", title: "Karar motorunun harcaması ölçülemedi", what: "Karar motorunun bu dönem ne kadar harcadığı okunamadı.", money: "Harcanmamış olduğu VARSAYILMADI: çağrı yapılmadı, para harcanmadı ve yeni pozisyon açılmadı. Çıkış ve borsadaki koruma emirleri sürüyor.", next: "Kayıt okunduğunda harcama yeniden ölçülür ve karar motoru kendiliğinden çalışır." },
  RISK_SETTINGS_UNREADABLE: { level: "WARN", title: "Risk ayarları okunamıyor", what: "Kaldıraç tavanını, vadeli işlem şalterini, açığa satış kipini ve vadeli maliyet eşiğini tutan ayar satırı okunamadı.", money: "Vadeli işlem yolu açılmadı: kaldıraçlı hiçbir emir gönderilmedi ve hiçbir varsayılan tavan uydurulmadı. Spot çıkışların ve borsadaki koruma emirlerinin bundan etkilenmedi: onlar bu ayara hiç bakmaz.", next: "Ayar satırı okunur okunmaz motor kaldığı yerden sürer. Bugün vadeli işlem hesabı zaten kapalıdır; bu uyarı bir para kaybı anlatmıyor." },
  BRAIN_SETTINGS_UNREADABLE: { level: "WARN", title: "Karar motorunun ayarları okunamıyor", what: "Hangi modelin, hangi sıklıkta ve ne kadar veriyle çalışacağını söyleyen ayar okunamadı.", money: "Karar motoru çağrılmadı: bunun için para harcanmadı ve yeni pozisyon açılmadı. Varsayılan bir ayara DÜŞÜLMEDİ, çünkü maliyeti bilinmeyen ayarla para harcanmaz.", next: "Ayar okunduğunda karar motoru kendiliğinden çalışır; çıkış ve koruma bu arada hiç etkilenmedi." },
  BRAIN_RUN_UNRECORDED: { level: "WARN", title: "Karar motorunun çağrısı kaydedilemedi", what: "Karar motorunun çağrı kaydı yazılamadı ya da okunamadı; kaydı tutulamayan çağrının maliyeti de sayılamaz.", money: "Kayıtsız çağrı yapılmadı ya da üretilen kural kullanılmadı: yeni pozisyon açılmadı. Çıkış ve borsadaki koruma emirleri sürüyor.", next: "Kayıt deposu döndüğünde karar motoru kendiliğinden çalışır." },
  BRAIN_INPUT_SECRET: { level: "ALARM", title: "Karar motoruna gidecek metinde sır deseni bulundu", what: "Karar motoruna gönderilecek girdide anahtar ya da parola benzeri bir desen görüldü; çağrı yapılmadı.", money: "Para harcanmadı ve yeni pozisyon açılmadı. Daha önemlisi: bu desen dışarıya gönderilmedi.", next: "Bu bir emniyet durması. Paneldeki sicil kaydını gördüğünü bize bildir; desenin girdinin hangi alanından geldiği orada yazılı." },
  MARKET_FEED_DOWN: { level: "WARN", title: "Piyasa fiyat akışı kesik", what: "Borsanın fiyat akışı okunamadı.", money: "Fiyat bilinmeden yeni pozisyon açılmıyor. Borsadaki koruma emirleri bizim akışımıza bağlı değil; tetiklenmeleri gerekiyorsa tetiklenirler.", next: "Akış döndüğünde fiyat değerlendirmesi kaldığı yerden sürer." },
  USER_STREAM_LOST: { level: "WARN", title: "Emir bildirim kanalı koptu", what: "Borsanın emir dolumlarını anında bildirdiği kanal kurulamadı ya da koptu. Borsayı sürekli yoklamaya geçilmedi: yoklama hem çağrı bütçesi harcar hem de sessiz bir yanlışlığı gizler.", money: "Dolumlar bu kanal dönene kadar kaydımıza anında düşmez. Borsadaki koruma emirleri kanaldan bağımsız çalışır.", next: "Kanal kendiliğinden yeniden kurulur. Bu arada koruma denetleyicisi emirleri borsaya tek tek sorarak görür." },
  CHAIN_BREAK: { level: "WARN", title: "Motorun sürekliliği koptu", what: "Motorun turunu devralması gereken halka devralmadı; nöbetçi zinciri yeniden kurdu.", money: "Kopuk geçen sürede yeni pozisyon açılmadı ve çıkış değerlendirilmedi. Borsadaki koruma emirleri bu boşlukta da yerindeydi.", next: "Nöbetçi kendiliğinden yeniden dener; tur yeniden başlayınca bu uyarı kalkar." },
  TICK_MISSED: { level: "WARN", title: "Motorun turu atlandı", what: "Motorun düzenli turu beklenen aralıkta koşmadı; arada bir boşluk var.", money: "Atlanan turda çıkış ve giriş değerlendirilmedi. Borsadaki koruma emirleri bu boşlukta da yerindeydi ve tetiklenmeleri gerekiyorsa tetiklendiler.", next: "Tur kendiliğinden yeniden başlar. Paneldeki gecikme satırı boşluğu rakamla gösterir." },
  PERMIT_REFRESH_FAILED: { level: "WARN", title: "Motorun çalışma izni tazelenemedi", what: "Çalışma izni kalıcı kayıttan tazelenemedi; izin uzatılmadı.", money: "Motor şimdilik çalışıyor; izin süresi dolduğunda kendiliğinden durur ve yeni pozisyon açmaz. Borsadaki koruma emirleri her hâlde yerinde kalır.", next: "Kalıcı kayıt döndüğünde izin kendiliğinden uzar. Dönmezse motoru yeniden başlatman gerekir." },
  POSITIONS_UNKNOWN: { level: "ALARM", title: "Açık pozisyonların durumu okunamıyor", what: "Motorun her turda okuduğu pozisyon özeti ne hızlı depodan ne de kalıcı kayıttan okunabildi.", money: "Motor bu durumda hiçbir iş yapmıyor: yeni pozisyon açmıyor, çıkış değerlendirmiyor. Pozisyon olmadığı VARSAYILMADI. Borsadaki koruma emirleri duruyor.", next: "Depolardan biri döndüğünde özet yeniden kurulur ve motor kaldığı yerden sürer." },
  POSITION_REFRESH_FAILED: { level: "WARN", title: "Pozisyon özeti tazelenemedi", what: "Pozisyon özeti kalıcı kayıtla karşılaştırılamadı; özet uzatılmadı.", money: "Motor şimdilik çalışıyor; özetin süresi dolduğunda durum bilinmiyor sayılır ve iş yapılmaz. Borsadaki koruma emirleri duruyor.", next: "Kalıcı kayıt döndüğünde özet kendiliğinden tazelenir." },
  POSITION_COPY_MISMATCH: { level: "WARN", title: "Pozisyon özeti kalıcı kayıtla uyuşmadı", what: "Hızlı depodaki pozisyon özeti ile kalıcı kayıt farklı çıktı; kalıcı kayıt doğru kabul edildi ve özet yeniden yazıldı.", money: "Tutarlı bir okuma yapılana kadar yeni pozisyon açılmıyor. Çıkış ve borsadaki koruma emirleri sürüyor.", next: "Bir sonraki karşılaştırma tutarlı çıkarsa giriş kendiliğinden yeniden açılır." },
  POSITION_COPY_STALE: { level: "WARN", title: "Pozisyon değişimi özete yazılamadı", what: "Pozisyonda olan değişiklik hızlı depodaki özete yazılamadı; özet silindi ve bir sonraki tur onu kalıcı kayıttan yeniden kurar.", money: "Kalıcı kayıt gerçektir ve pozisyonların yönetimi değişmedi. Özet kurulana kadar yeni pozisyon açılmıyor.", next: "Bir sonraki tur özeti yeniden kurar; bir şey yapman gerekmiyor." },
  LOCK_UNAVAILABLE: { level: "WARN", title: "İcra kilidi deposu erişilemiyor", what: "Aynı sinyalin iki kez icra edilmesini önleyen kilit okunamadı; icra yapılmadı.", money: "Kilit olmadan emir gönderilmez: iki kez açılmış bir pozisyonun maliyeti, hiç açılmamış bir pozisyonun maliyetinden büyüktür. Çıkış ve borsadaki koruma emirleri sürüyor.", next: "Depo döndüğünde motor kaldığı yerden sürer." },
  RECORD_UNAVAILABLE: { level: "WARN", title: "Emir kayıt deposu okunamıyor", what: "Gönderilecek emrin daha önce gönderilip gönderilmediği okunamadı; gönderim yapılmadı.", money: "Kaydı okunamayan emir gönderilmez: aynı emri iki kez göndermenin maliyeti hiç göndermemekten büyüktür. Çıkış ve borsadaki koruma emirleri sürüyor.", next: "Depo döndüğünde motor kaldığı yerden sürer." },
  THROTTLE_UNAVAILABLE: { level: "WARN", title: "Borsaya çağrı sayacı çalışmıyor", what: "Borsaya yapılan çağrıların ağırlığını sayan bileşen çalışmadığı için çağrı hiç gönderilmedi.", money: "Sayaç olmadan çağrı yapılmaz: borsanın erişimi kapatması, bir turu kaçırmaktan pahalıdır. Borsadaki koruma emirleri yerinde duruyor.", next: "Sayaç deposu döndüğünde motor kaldığı yerden sürer." },
  RECORD_FAILED_AFTER_SEND: { level: "ALARM", title: "Borsa yanıt verdi, kaydı tutulamadı", what: "Borsa çağrıya yanıt verdi ama yanıtın kendi defterimize yazılması düştü. Yanıtın kendisi sicile taşındı, atılmadı.", money: "Borsadaki durum geçerlidir; bizim defterimizde bu işlemin satırı eksik kaldı. Ödenen komisyon borsada gerçekleşti.", next: "Paneldeki sicil kaydı borsanın yanıtını olduğu gibi taşıyor; motor bir sonraki turda defteri borsayla karşılaştırır." },
  ORDER_RULES_UNAVAILABLE: { level: "WARN", title: "Borsanın emir kuralları okunamadı", what: "Borsanın o çift için istediği en küçük tutar, adım ve fiyat kuralları okunamadı; emir gönderilmedi.", money: "Kuralı bilinmeyen emir gönderilmez: borsanın reddettiği her emir boşa giden bir turdur. Çıkış ve borsadaki koruma emirleri sürüyor.", next: "Kurallar okunduğunda motor kaldığı yerden sürer." },
  ORDER_RULE_VIOLATION: { level: "WARN", title: "Emir borsanın kurallarına uymuyor", what: "Hazırlanan emir, borsanın o çift için koyduğu en küçük tutar, adım ya da fiyat kuralına uymadı; gönderilmeden önce durduruldu.", money: "Emir borsaya hiç gitmedi, komisyon ödenmedi. Kurala uymayan emri göndermek yalnız zaman kaybettirirdi.", next: "Bir şey yapman gerekmiyor. Paneldeki sicil kaydı hangi kuralın tutmadığını söyler." },
  ENTRY_CLOSED: { level: "INFO", title: "Giriş yolu kapalı", what: "Pozisyon açma yolu kapalı olduğu için emir gönderilmedi.", money: "Yeni pozisyon açılmıyor ve komisyon harcanmıyor. Açık pozisyonların yönetimi ve borsadaki koruma emirleri bundan etkilenmiyor.", next: "Giriş yolu açılmadan pozisyon açılmaz; bu bir arıza değil, kasıtlı bir ayardır." },
  COST_UNMEASURABLE: { level: "WARN", title: "İşlem maliyeti ölçülemedi", what: "Bir turun gidiş-dönüş maliyetini kuran kalemlerden biri (komisyon, alış-satış farkı ya da derinlik) ölçülemedi.", money: "Maliyeti bilinmeyen işleme girilmez: beklenen hareketin maliyeti kaç kat aştığı hesaplanamıyor. Çıkış ve borsadaki koruma emirleri sürüyor.", next: "Ölçüm döndüğünde giriş kendiliğinden açılır." },
  ORDER_REJECTED: { level: "WARN", title: "Borsa emri reddetti", what: "Emir borsaya ulaştı ve borsa onu bir iş kuralıyla reddetti: filtre, bakiye ya da zaman damgası.", money: "Emir oluşmadı ve komisyon ödenmedi. Pozisyon açılmadı.", next: "Paneldeki sicil kaydı borsanın yanıtını taşıyor. Sebep bakiyeyse hesaba ekleme yapman gerekir." },
  STAMP_STALE: { level: "WARN", title: "Emrin zaman damgası yaşlandı", what: "İmzalı emrin zaman damgası, gönderim anına gelmeden borsanın kabul penceresinin sınırına yaklaştı; emir gönderilmedi.", money: "Emir gönderilmedi, komisyon ödenmedi. Yaşlı damgalı emri göndermek borsanın reddiyle sonuçlanırdı.", next: "Bir sonraki tur damgayı yeniden basar; bir şey yapman gerekmiyor." },
  CLOCK_UNSYNCED: { level: "WARN", title: "Borsanın saati okunamadı", what: "İmzalı çağrının zaman damgası borsanın saatinden türer; borsanın saati okunamadı ya da ölçüm güvenilir çıkmadı.", money: "Yanlış damgalı emir gönderilmedi: borsa onu reddeder ve tur boşa giderdi. Çıkış ve borsadaki koruma emirleri sürüyor.", next: "Saat okunduğunda motor kaldığı yerden sürer." },
  CLOCK_SKEW_EXCEEDED: { level: "WARN", title: "Sunucumuzun saati kaymış", what: "Yerel saatin borsa saatinden sapması kabul edilen sınırı aştı; imzalı çağrı yapılmadı.", money: "Sapmış saatle imzalanan emri borsa reddeder. Emir gönderilmedi, komisyon ödenmedi.", next: "Sapma kendiliğinden düzelir; düzelmezse paneldeki sicil kaydını gördüğünü bize bildir." },
  REENTRY_UNMEASURABLE: { level: "WARN", title: "Yeniden giriş kuralı ölçülemedi", what: "Aynı çifte kaç kez girildiği ya da soğuma süresinin dolup dolmadığı okunamadı.", money: "Sayılamayan tur kuralı yeniden girişi serbest bırakmaz: sık giriş-çıkış sessiz komisyon zararı üretir. Çıkış ve borsadaki koruma emirleri sürüyor.", next: "Kayıt okunduğunda giriş kendiliğinden açılır." },
} as const satisfies Partial<Record<StopReasonCode, NotifyText>>;
/** KABUL KRİTERİ DERLEYİCİYE BAĞLI: bildirim gerektiren HER sebebin metni yazılmış olmak zorundadır. Eksik varsa `never`'a `true` atanamaz ve DERLEME DÜŞER. */
type MissingNotifyText = Exclude<NotifiableCode, keyof typeof NOTIFY_TEXT>;
export const EVERY_NOTIFIABLE_HAS_TEXT: [MissingNotifyText] extends [never] ? true : never = true;
/** TUR 65 — BİLDİRİMLİ İSTEK TÜRLERİNİN METNİ (durma sicilinde değiller ⇒ `NOTIFY_TEXT`e giremezler). `Record` TAMDIR: bildirimli sınıfa yazılan her tür metin taşımak zorundadır (derleyici). Rakam yok (U-2). */
export const REQUEST_NOTIFY_TEXT = {
  ENTRY_SWITCH_OPENED: { level: "WARN", title: "Giriş şalteri açıldı", what: "Panelden giriş şalteri açıldı; açma onay ekranı ve tek kullanımlık kod doğrulaması geçti.", money: "Motor artık uygun fırsat bulduğunda kendi kararıyla gerçek parayla giriş emri gönderebilir. Emir çıkması için Binance anahtarı, sermaye ve risk ayarları da dolu olmalıdır.", next: "Bunu sen yaptıysan bir şey yapman gerekmez. Sen yapmadıysan panelden şalteri hemen kapat ve parolanı değiştir; durdurma ekranı oturum istemez." },
} as const satisfies Record<NotifiedRequestKind, NotifyText>;

/** U-2 — KİLİT EKRANI YÜKÜ: kapalı alan listesi. Tutar/bakiye/pozisyon büyüklüğü taşıyacak alan yok; üç cümle (`detail`) bu yüke HİÇ girmez. */
export const LOCK_SCREEN_FIELDS = ["display.title", "display.body", "route.code", "route.level", "route.at", "route.producedAt", "route.undismissable"] as const;
export type PushPayload = { display: { title: string; body: string }; route: { code: string; level: Level; at: string; producedAt: string; undismissable: boolean } };
export const payloadFields = (p: PushPayload): string[] => [...Object.keys(p.display).map((k) => `display.${k}`), ...Object.keys(p.route).map((k) => `route.${k}`)].sort();
export const payloadClosed = (p: PushPayload): boolean => payloadFields(p).join(",") === [...LOCK_SCREEN_FIELDS].sort().join(",");
/** Kilit ekranı notu: seviyeye göre SABİT cümle. Veri taşımaz, rakam içermez ve rakamın neden orada olmadığını söyler (U-2). */
export const LOCK_HINT: Record<Level, string> = {
  ALARM: "Uygulamayı aç: ne olduğu, paraya etkisi ve ne yapılacağı orada yazılı. Tutar, bakiye ve pozisyon büyüklüğü kilit ekranında gösterilmez.",
  WARN: "Ayrıntı uygulamada: ne olduğu, paraya etkisi ve ne yapılacağı orada yazılı. Tutar, bakiye ve pozisyon büyüklüğü kilit ekranında gösterilmez.",
  INFO: "Ayrıntı uygulamada. Tutar, bakiye ve pozisyon büyüklüğü kilit ekranında gösterilmez.",
};
export type BuiltNotification = { code: string; textWritten: boolean; level: Level; payload: PushPayload; detail: { what: string; money: string; next: string } };
/** BİLDİRİMİ KURAN TEK YOL. Sicilde olmayan kod → `null` (bildirim ÜRETİLMEZ). Sessiz sınıf (atlama) → `null` (bildirim GEREKMEZ). Sicilde olup metni yazılmamış sebep → sicilin ETİKETİ,
 *  uydurma metin değil; `textWritten:false` bunu söyler. `at` olayın zamanı, `producedAt` bildirimin kurulduğu an: yük hem ne zaman hem hangi olaydan doğduğunu (kod + zaman) taşır. */
export function buildNotification(code: string, at: Date, now: number): BuiltNotification | null {
  const meta = (STOP_REASONS as Record<string, { kind: string; label: string } | undefined>)[code];
  // Tur 65: bildirimli İSTEK türü (durma değil). Bildirimsiz istek türü ve sicil dışı kod aşağıda `null` olur — Tur 48'in "istek türü adı bildirim üretmez" kuralı bildirimsiz sınıf için AYNEN geçerli.
  const req = (REQUEST_KIND_NOTIFY as Record<string, string | undefined>)[code] === "bildirimli" ? (REQUEST_NOTIFY_TEXT as Record<string, NotifyText | undefined>)[code] : undefined;
  if (req !== undefined) return { code, textWritten: true, level: req.level, detail: { what: req.what, money: req.money, next: req.next },
    payload: { display: { title: req.title, body: LOCK_HINT[req.level] }, route: { code, level: req.level, at: at.toISOString(), producedAt: new Date(now).toISOString(), undismissable: undismissable(code) } } };
  if (meta === undefined || meta.kind === "POSITION_SKIPPED") return null;
  const written = (NOTIFY_TEXT as Partial<Record<string, NotifyText>>)[code];
  const t: NotifyText = written ?? { level: "WARN", title: meta.label, what: `Sicile şu kayıt düştü: ${meta.label}.`, money: "Bu kaydın paraya etkisi bu bildirimde ayrıca yazılmadı; ne yeni pozisyon açılmadığını ne de borsadaki koruma emirlerinin yerinde olduğunu varsay.", next: "Bu sebep için bildirim metni henüz yazılmadı; uygulamadaki sicil kaydı sebebi kendi etiketiyle gösterir." };
  return { code, textWritten: written !== undefined, level: t.level, detail: { what: t.what, money: t.money, next: t.next },
    payload: { display: { title: t.title, body: LOCK_HINT[t.level] }, route: { code, level: t.level, at: at.toISOString(), producedAt: new Date(now).toISOString(), undismissable: undismissable(code) } } };
}

export type SendResult = { ok: true; id: string } | { ok: false; error: string };
/** Taşıyıcı arayüzü: gerçek FCM köprüsü BUNUN ARKASINA yazılır — Tur 82: `./fcm.ts` (isteğe bağlı Firebase eklentisi, D2). */
export interface NotifyTransport { readonly name: string; send(payload: PushPayload): Promise<SendResult> }
/** KAPALI ARIZA: taşıyıcı yapılandırılmadığında gönderim BAŞARISIZ döner. "Gönderildi" saymak yasaktır (U-2); sonuç durma olayına yazılır (K-8). */
export const unconfiguredTransport = (): NotifyTransport => ({ name: "YAPILANDIRILMADI", send: async () => ({ ok: false, error: "bildirim kapalı: Firebase eklenmedi (isteğe bağlı eklenti, değişkenler boş)" }) });
/** TUR 82 (D2) — YARIM/BOZUK Firebase yapılandırması: KAPALI ARIZA. Gönderim yapılmaz, yalnız ADLAR söylenir (değer asla — S-2). */
export const misconfiguredTransport = (names: readonly string[]): NotifyTransport => ({ name: "YARIM_YAPILANDIRMA", send: async () => ({ ok: false, error: `Firebase değişkenleri eksik ya da bozuk (${names.join(", ")}): bildirim gönderilmedi` }) });
export type MutePreference = { readonly mutedCodes: readonly string[] };
/** KAPALI VARSAYILAN: hiçbir bildirim kapalı değil. Tur 28: kapatma tercihinin SAKLANDIĞI yer `notify_settings` (Neon); bu sabit yalnız "ayar okunamadı" ve kapı/kanarya yolunun karşılığıdır. */
export const NOTHING_MUTED: MutePreference = { mutedCodes: [] };
/** ÜRETİM TAŞIYICISI — çağıran seçmez, unutamaz (kapı: ikinci gönderim yolu KIRMIZI). Bugün TEK dal var: taşıyıcı yapılandırılmadı (madde 1 ölçümü). Köprü geldiğinde değişecek tek satır BURASIDIR. */
/** TUR 82 (G20 FCM kalemi · KARAR-DEFTERI 1 Eki 2026 D2): üç dal, ad sözleşmesinden (src/lib/env.ts `readFirebaseEnv`) — üç değişken BOŞ ⇒ YAPILANDIRILMADI (kapalı, hata yok) ·
 *  YARIM/BOZUK ⇒ YARIM_YAPILANDIRMA (kapalı arıza) · DOLU ⇒ FIREBASE (cihaz deposu yalnız burada kurulur; gönderim durdurma deposu bütçesiyle kesilir, K-7). `opts` yalnız kapı/kanarya içindir (S-9). */
export const defaultTransport = (fb: FirebaseEnv = readFirebaseEnv(), opts: { devices?: DeviceStore; endpoints?: { token: string; send: string } } = {}): NotifyTransport =>
  fb.state === "ON" ? fcmTransport(fb.cfg, { devices: opts.devices ?? prismaDeviceStore(), timeoutMs: NOTIFY_STORE_BUDGET_MS, endpoints: opts.endpoints })
    : fb.state === "INVALID" ? misconfiguredTransport(fb.names) : unconfiguredTransport();
/** Panelin bildirim durumu (Tur 82): yalnız durum ve ADLAR — değer, proje kimliği, e-posta TAŞIMAZ. */
export type NotifyStateView = { state: "OFF" | "ON" | "INVALID"; names: string[] };
export const notifyState = (fb: FirebaseEnv = readFirebaseEnv()): NotifyStateView => ({ state: fb.state, names: fb.state === "INVALID" ? [...fb.names] : [] });
export type NotifyDeps = { transport?: NotifyTransport; mute?: MutePreference; settings?: NotifySettingsStore; dedup?: DedupStore; now?: () => number };
export type Delivery = { sent: boolean; muted: boolean; suppressed: boolean; transport: string; id: string | null; error: string | null; sentence: string };
/** BİLDİRİMİ GÖNDEREN TEK YOL. Gönderilemeyen bildirim `sent:false` döner ve `sentence` durma olayının sebebine yazılır (çağıran onu düşüremez — kapı). Kuyruk ve yeniden deneme YOK (U-2).
 *  SIRA (Tur 28): ayar oku → KAPATILAMAZ MI (U-2: eleme ve kapatma ikisini de geçer) → kapatılmış mı → ELEME penceresi → gönder. Eleme yalnız AYNI sebebi keser; farklı sebep aynı anda gider.
 *  ELEME BİR EMNİYET KAPISI DEĞİLDİR: penceresi okunamazsa bildirim GİDER ve cümlede "eleme penceresi okunamadı" yazar (kaybolan bildirim, yinelenenden kötüdür). */
export async function deliverNotification(n: BuiltNotification, deps: NotifyDeps = {}): Promise<Delivery> {
  const transport = deps.transport ?? defaultTransport(), now = deps.now ?? Date.now;
  const loaded = await loadNotifySettings(deps.settings ?? prismaNotifySettingsStore());
  const pref = deps.mute ?? { mutedCodes: loaded.settings.mutedCodes };
  const note = loaded.readable ? "" : " · ayar okunamadı: hiçbir sebep kapatılmadı ve eleme yapılmadı";
  const done = (d: Omit<Delivery, "sentence">, sentence: string): Delivery => ({ ...d, sentence: sentence + note });
  const cannotMute = undismissable(n.code);
  if (pref.mutedCodes.includes(n.code) && !cannotMute) return done({ sent: false, muted: true, suppressed: false, transport: transport.name, id: null, error: null }, "bildirim=SESSİZE ALINDI (sahip bu sebebi kapattı)");
  // ELEME — SEBEBE GÖRE AYRI PENCERE (iş sahibi kararı K1 = [C], 2026-09-17; Tur 28'in tam muafiyetinin yerine): kapatılamaz sınıf KENDİ penceresiyle, diğerleri kendi penceresiyle.
  // ARTIK RİSK (bilerek alınan bedel): para güvenliği bildirimi pencere içinde kapatılamaz penceresi kadar (bugün 2 dakika) GECİKEBİLİR — U-2'nin "gecikmiş bildirim yok" sözüne dokunur.
  const cls = cannotMute ? "kapatilamaz" : "kapatilabilir", windowMs = cannotMute ? loaded.settings.dedupWindowUndismissableMs : loaded.settings.dedupWindowMs;
  const v = windowMs > 0 ? await (deps.dedup ?? upstashDedupStore()).firstInWindow(cls, n.code, windowMs, now()) : { first: true, remainingMs: null, unreadable: false };
  if (!v.first) return done({ sent: false, muted: false, suppressed: true, transport: transport.name, id: null, error: null },
    `bildirim=ELENDİ (aynı sebep ${human(windowMs)} içinde bir kez bildirilir; bu pencerede zaten bildirildi${v.remainingMs === null ? "" : `, pencerenin bitmesine ${human(v.remainingMs)}`})`);
  const dedupNote = v.unreadable ? ", eleme penceresi okunamadı: eleme yapılmadı" : "";
  let r: SendResult;
  try { r = await transport.send(n.payload); } catch (e) { r = { ok: false, error: `taşıyıcı çağrısı düştü: ${e instanceof Error ? e.message : String(e)}` }; }
  return r.ok ? done({ sent: true, muted: false, suppressed: false, transport: transport.name, id: r.id, error: null }, `bildirim=GÖNDERİLDİ (taşıyıcı ${transport.name}${dedupNote})`)
    : done({ sent: false, muted: false, suppressed: false, transport: transport.name, id: null, error: r.error }, `bildirim=GÖNDERİLEMEDİ (taşıyıcı ${transport.name}, ${r.error}${dedupNote})`);
}
